[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Browse"
  pageRef = "browse"
  weight = 30

[[main]]
  name = "Tools"
  pageRef = "tools"
  weight = 40
