name: yalin.dev CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - draft
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          COMMIT_SHA="${GITHUB_SHA:0:7}"

          IMAGE_LABEL=""
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            IMAGE_LABEL="latest"
          elif [[ "$GITHUB_REF" == "refs/heads/dev" ]]; then
            IMAGE_LABEL="dev"
          elif [[ "$GITHUB_REF" == "refs/heads/draft" ]]; then
            IMAGE_LABEL="draft"
          elif [[ "$GITHUB_REF" == "refs/tags/"* ]]; then
            IMAGE_LABEL="${GITHUB_REF##*/}"
          fi

          IMAGE_TAG="ygunayer/yalin.dev:$COMMIT_SHA"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

          if [[ "$ADDITIONAL_TAG" != "" ]]; then
            LABELED_TAG="ygunayer/yalin.dev:$ADDITIONAL_TAG"
            docker tag $IMAGE_TAG $LABELED_TAG
            docker push $LABELED_TAG
          fi

      - name: Logout from Docker Hub
        run: docker logout
